import Head from 'next/head'
// import styles from '../styles/Home.module.css'
import { GetServerSideProps } from 'next'

type Props = {
  ids?: string[];
};

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {props.ids?.map(id => (
            <div key={id}>
              <img key={id} src={`/api/images/${id}`}/>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}

const fetchIDs = async () => {
  const listRes = await (await fetch("http://localhost:41595/api/item/list")).json()
  const ids: string[] = listRes.data.map((item: any) => item.id)
  return ids
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const ids = await fetchIDs()

  const props: Props = {
    ids,
  };

  return {
    props: props,
  };
};
